version: "2.4"

services:

  client:
    build:
      context: ./dockerfiles
      dockerfile: client
    image: goipsec-client
    container_name: client
    mac_address: "02:42:ac:11:00:10"
    cap_add:
      - ALL
    depends_on:
      - vpn-gateway
    command: sh -c 'ip route delete default && ip route add default via 173.17.17.20 && ip route delete 173.17.17.0/24 && ip route show && curl web-server --connect-timeout 5'
    networks: 
      default:
        ipv4_address: "173.17.17.10"
        ipv6_address: "2001:db8:23:42:1::10"

  vpn-gateway:
    build:
      context: ./dockerfiles
      dockerfile: vpn
    image: goipsec-vpn
    container_name: vpn-gateway
    mac_address: "02:42:ac:11:00:20"
    depends_on:
      - vpn-server
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/.go/src/goipsec:/go/src/goipsec
    command: sh -c 'iptables -I FORWARD -s 173.17.17.10 -j DROP && tcpdump -w /go/src/goipsec/docker/logs/vpn-gateway.pcap'
    networks: 
      default:
        ipv4_address: "173.17.17.20"
        ipv6_address: "2001:db8:23:42:1::20"

  vpn-server:
    build:
      context: ./dockerfiles
      dockerfile: vpn
    image: goipsec-vpn
    container_name: vpn-server
    mac_address: "02:42:ac:11:00:30"
    depends_on:
      - web-server
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/.go/src/goipsec:/go/src/goipsec
    command: sh -c 'rm -f /go/src/goipsec/cmd/ipsec/main && cd /go/src/goipsec/cmd/ipsec/ && go build main.go && tcpdump -w /go/src/goipsec/docker/logs/vpn-server.pcap'
    # healthcheck:
    #   test: ["CMD-SHELL", "test -f /go/src/goipsec/cmd/ipsec/main"]
    #   interval: 1s
    #   timeout: 3s
    #   retries: 3
    networks: 
      default:
        ipv4_address: "173.17.17.30"
        ipv6_address: "2001:db8:23:42:1::30"

  web-server:
    build:
      context: ./dockerfiles
      dockerfile: web-server
    image: goipsec-web-server
    container_name: web-server
    mac_address: "02:42:ac:11:00:40"
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/.go/src/goipsec/docker/logs/web-server.pcap:/ipsec/web-server.pcap
    command: sh -c 'nginx && tcpdump -w /ipsec/web-server.pcap'
    networks:
      default:
        ipv4_address: "173.17.17.40"
        ipv6_address: "2001:db8:23:42:1::40"

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "173.17.17.0/24"
        - subnet: "2001:db8:23:42:1::/80"