version: "2.4"

services:

  client:
    image: goipsec
    container_name: client
    mac_address: "02:42:ac:11:00:10"
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/bsc-thesis/cmd/ipsec-server:/ipsec
    depends_on:
      - local-gateway
    command: sh -c "ip route add 173.17.17.12/32 via 173.17.17.11 && sleep 2147483647"
    networks: 
      default:
        ipv4_address: "173.17.17.10"
        ipv6_address: "2001:db8:23:42:1::10"

  local-gateway:
    image: goipsec
    container_name: local-gateway
    mac_address: "02:42:ac:11:00:11"
    depends_on:
      - remote-gateway
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/bsc-thesis/cmd/ipsec-server:/ipsec
    command: sh -c '
              echo "net.ipv4.ip_forward = 0" >> /etc/sysctl.conf &&
              sysctl -p &&
              iptables -t mangle -A POSTROUTING -p icmp --icmp-type redirect -j DROP &&
              iptables -I FORWARD -d 173.17.17.12 -j DROP && 
              tcpdump -vvv -XX udp'
    networks: 
      default:
        ipv4_address: "173.17.17.11"
        ipv6_address: "2001:db8:23:42:1::11"

  remote-gateway:
    image: goipsec
    container_name: remote-gateway
    mac_address: "02:42:ac:11:00:12"
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/bsc-thesis/cmd/ipsec-server:/ipsec
    command: tcpdump -vvv -XX esp
    networks: 
      default:
        ipv4_address: "173.17.17.12"
        ipv6_address: "2001:db8:23:42:1::12"

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "173.17.17.0/24"
        - subnet: "2001:db8:23:42:1::/80"