version: "2.4"

services:

  client:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-client
    image: goipsec-client
    container_name: client
    mac_address: "02:42:ac:11:00:10"
    cap_add:
      - ALL
    depends_on:
      - client-gateway
    command: sh -c 'ip route add 173.17.17.13/32 via 173.17.17.11 && sleep 2147483647'
    networks: 
      default:
        ipv4_address: "173.17.17.10"
        ipv6_address: "2001:db8:23:42:1::10"

  client-gateway:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-vpn
    image: goipsec-gateway
    container_name: client-gateway
    mac_address: "02:42:ac:11:00:11"
    depends_on:
      - vpn-gateway
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/bsc-thesis/cmd/ipsec-server:/ipsec
    command: sh -c '
              iptables -t mangle -A POSTROUTING -p icmp --icmp-type redirect -j DROP &&
              iptables -I FORWARD -d 173.17.17.13 -j DROP && 
              tcpdump -vvv -xx "(udp and src 173.17.17.10) or (esp and src 2001:db8:23:42:1::12)"'
    networks: 
      default:
        ipv4_address: "173.17.17.11"
        ipv6_address: "2001:db8:23:42:1::11"

  vpn-gateway:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-vpn
    image: goipsec-gateway
    container_name: vpn-gateway
    mac_address: "02:42:ac:11:00:12"
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/bsc-thesis/cmd/ipsec-server:/ipsec
    command: sh -c '
              iptables -t mangle -A POSTROUTING -p icmp --icmp-type redirect -j DROP &&
              iptables -I FORWARD -d 173.17.17.10 -j DROP && 
              tcpdump -vvv -xx "(udp and src 173.17.17.13) or (esp and src 2001:db8:23:42:1::11)"'
    networks: 
      default:
        ipv4_address: "173.17.17.12"
        ipv6_address: "2001:db8:23:42:1::12"

  server:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-client
    image: goipsec-client
    container_name: server
    mac_address: "02:42:ac:11:00:13"
    cap_add:
      - ALL
    depends_on:
      - vpn-gateway
    command: sh -c 'ip route add 173.17.17.10/32 via 173.17.17.12 && tcpdump -vvv -xx "(udp and src 173.17.17.10)"'
    networks:
      default:
        ipv4_address: "173.17.17.13"
        ipv6_address: "2001:db8:23:42:1::13"

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "173.17.17.0/24"
        - subnet: "2001:db8:23:42:1::/80"