version: "2.4"

services:

  client:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-client
    image: goipsec-client
    container_name: client
    mac_address: "02:42:ac:11:00:10"
    cap_add:
      - ALL
    depends_on:
      - client-gateway
    command: sh -c 'ip route add 173.17.17.13/32 via 173.17.17.11 && 
              sleep 5 &&
              (echo -n "hello" | nc -u -w 1 173.17.17.13 6000) &&
              (echo -n "hello again" | nc -u -w 1 173.17.17.13 6000) &&
              (echo -n "final hello" | nc -u -w 1 173.17.17.13 6000)'
    networks: 
      default:
        ipv4_address: "173.17.17.10"
        ipv6_address: "2001:db8:23:42:1::10"

  client-gateway:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-vpn
    image: goipsec-gateway
    container_name: client-gateway
    mac_address: "02:42:ac:11:00:11"
    depends_on:
      - vpn-gateway
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/.go/src/goipsec:/go/src/goipsec
    command: sh -c '
              iptables -t mangle -A POSTROUTING -p icmp --icmp-type redirect -j DROP &&
              iptables -I FORWARD -d 173.17.17.13 -j DROP && 
              go build /go/src/goipsec/cmd/ipsec/main.go &&
              (/go/src/goipsec/cmd/ipsec/main &) &&
              tcpdump -w /go/src/goipsec/docker/logs/client-gateway-logs.pcap'
    networks: 
      default:
        ipv4_address: "173.17.17.11"
        ipv6_address: "2001:db8:23:42:1::11"

  vpn-gateway:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-vpn
    image: goipsec-gateway
    container_name: vpn-gateway
    mac_address: "02:42:ac:11:00:12"
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/.go/src/goipsec/docker/logs/vpn-gateway-logs.pcap:/ipsec/vpn-gateway-logs.pcap
    command: sh -c '
              iptables -t mangle -A POSTROUTING -p icmp --icmp-type redirect -j DROP &&
              iptables -I FORWARD -d 173.17.17.10 -j DROP && 
              tcpdump -w vpn-gateway-logs.pcap'
    networks: 
      default:
        ipv4_address: "173.17.17.12"
        ipv6_address: "2001:db8:23:42:1::12"

  vpn-server:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-client
    image: goipsec-client
    container_name: vpn-server
    mac_address: "02:42:ac:11:00:13"
    cap_add:
      - ALL
    volumes:
      - /home/bogdan/.go/src/goipsec/docker/logs/vpn-server-logs.pcap:/ipsec/vpn-server-logs.pcap
    depends_on:
      - vpn-gateway
    command: sh -c 'ip route add 173.17.17.10/32 via 173.17.17.12 && tcpdump -w vpn-server-logs.pcap'
    networks:
      default:
        ipv4_address: "173.17.17.13"
        ipv6_address: "2001:db8:23:42:1::13"

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "173.17.17.0/24"
        - subnet: "2001:db8:23:42:1::/80"